#pragma once

#include <cstddef>
#include <cstdint>
#include <string>

// GENERATED COMPANION CAPABILITIES - do not edit by hand
// Generated by scripts/build.py from product/v2/companion_capabilities.json.

constexpr int COMPANION_CAPABILITY_VERSION = 2;
constexpr int COMPANION_PROTOCOL_VERSION = 3;
constexpr const char *COMPANION_PROTOCOL_PATH = "/companion/v3";
constexpr size_t COMPANION_MAXIMUM_TEXT_FRAME_BYTES = 16384;
constexpr size_t COMPANION_MAXIMUM_ARTWORK_BYTES = 262144;
constexpr size_t COMPANION_ARTWORK_CHUNK_BYTES = 12288;
constexpr uint32_t COMPANION_PAIRING_WINDOW_SECONDS = 900;

constexpr bool COMPANION_BROWSER_STARTS_PAIRING = true;
constexpr bool COMPANION_BROWSER_EXPOSES_PAIRING_CODE = true;
struct CompanionProtocolMessagePolicy { const char *id; const char *direction; const char *authorization; };
inline constexpr CompanionProtocolMessagePolicy COMPANION_PROTOCOL_MESSAGES[] = {
  {"hello", "panel_to_mac", "public"},
  {"pair.request", "mac_to_panel", "pairing_window"},
  {"pair.accepted", "panel_to_mac", "pairing_window"},
  {"auth.request", "mac_to_panel", "paired"},
  {"auth.accepted", "panel_to_mac", "paired"},
  {"capabilities", "mac_to_panel", "session"},
  {"catalogue.request", "panel_to_mac", "session"},
  {"catalogue.page", "mac_to_panel", "session"},
  {"action.invoke", "panel_to_mac", "session"},
  {"action.result", "bidirectional", "session"},
  {"value.set", "panel_to_mac", "session"},
  {"value.state", "mac_to_panel", "session"},
  {"focus.changed", "mac_to_panel", "session"},
  {"timezone.changed", "mac_to_panel", "session"},
  {"now_playing", "mac_to_panel", "session"},
  {"system_metrics", "mac_to_panel", "session"},
  {"artwork.begin", "mac_to_panel", "session"},
  {"artwork.ack", "panel_to_mac", "session"},
  {"artwork.end", "mac_to_panel", "session"},
  {"artwork.abort", "bidirectional", "session"},
  {"artwork.request", "panel_to_mac", "session"},
  {"error", "bidirectional", "public"},
};

struct CompanionCardModeCapability { const char *id; const char *label; const char *capability; const char *default_icon; };
inline constexpr CompanionCardModeCapability COMPANION_CARD_MODES[] = {
  {"app", "Launch app", "applications", "Monitor"},
  {"shortcut", "Keyboard shortcut", "keyboard_shortcuts", "Shortcut Command"},
  {"url", "Open URL", "applications", "Web"},
  {"folder", "Open folder", "folders", "Folder Outline"},
  {"media", "Media control", "media_actions", "Play Pause"},
  {"stats", "Stats", "system_metrics", "Gauge"},
  {"window", "Window control", "window_actions", "Monitor"},
};

struct CompanionWindowCapability { const char *id; const char *label; };
inline constexpr CompanionWindowCapability COMPANION_WINDOW_CAPABILITIES[] = {
  {"window.close", "Close"},
  {"window.minimize", "Minimise"},
  {"window.hide", "Hide App"},
  {"window.fullscreen", "Full Screen"},
  {"window.fill", "Fill Desktop"},
  {"window.center", "Centre"},
  {"window.left", "Left"},
  {"window.right", "Right"},
  {"window.top", "Top"},
  {"window.bottom", "Bottom"},
  {"window.restore", "Return to Previous Size"},
  {"window.arrange.left-right", "Left & Right"},
  {"window.arrange.right-left", "Right & Left"},
  {"window.arrange.top-bottom", "Top & Bottom"},
  {"window.arrange.bottom-top", "Bottom & Top"},
  {"window.arrange.left-quarters", "Left & Quarters"},
  {"window.arrange.right-quarters", "Right & Quarters"},
  {"window.arrange.top-quarters", "Top & Quarters"},
  {"window.arrange.bottom-quarters", "Bottom & Quarters"},
};

struct CompanionMetricCapability { const char *id; const char *label; const char *label_key; const char *unit; };
inline constexpr CompanionMetricCapability COMPANION_METRIC_CAPABILITIES[] = {
  {"stat.cpu", "Processor", "processor", "%"},
  {"stat.memory", "Memory", "memory", "%"},
  {"stat.memory_free", "Memory", "memory", "%"},
  {"stat.storage", "Storage", "storage", "%"},
  {"stat.storage_free", "Storage", "storage", "%"},
  {"stat.battery", "Battery", "battery", "%"},
  {"stat.network_throughput", "Network", "network_throughput", "MB/s"},
};

inline constexpr const char *COMPANION_MEDIA_ACTION_IDS[] = {
  "media.play_pause",
  "media.previous",
  "media.next",
};

constexpr const char *COMPANION_MEDIA_PLAY_PAUSE_ACTION = "media.play_pause";

inline const CompanionWindowCapability *companion_window_capability(const std::string &id) {
  for (const auto &item : COMPANION_WINDOW_CAPABILITIES) if (id == item.id) return &item;
  return nullptr;
}

inline const CompanionMetricCapability *companion_metric_capability(const std::string &id) {
  for (const auto &item : COMPANION_METRIC_CAPABILITIES) if (id == item.id) return &item;
  return nullptr;
}

inline bool companion_generated_media_action_valid(const std::string &id) {
  for (const auto *item : COMPANION_MEDIA_ACTION_IDS) if (id == item) return true;
  return false;
}
