// GENERATED COMPANION CAPABILITIES - do not edit by hand
// Generated by scripts/build.py from product/v2/companion_capabilities.json.

import CoreGraphics

struct CompanionWindowActionCapability {
    let key: String?
    let flags: CGEventFlags
    let minimumMacOS: Int
    let menuPaths: [[String]]
}

enum CompanionCapabilities {
    static let version = 4
    static let protocolVersion = 4
    static let protocolPath = "/companion/v4"
    static let maximumTextFrameBytes = 16384
    static let maximumArtworkBytes = 262144
    static let artworkChunkBytes = 12288
    static let appIconChunkBytes = 4096
    static let appIconSide = 144
    static let appIconPixelBytes = 62208
    static let appIconsCapability = "app_icons"
    static let appIconsAlphaCapability = "app_icons_alpha"
    static let pairingWindowSeconds = 900
    static let protocolMessages: Set<String> = [
        "hello",
        "pair.request",
        "pair.accepted",
        "auth.request",
        "auth.accepted",
        "capabilities",
        "catalogue.request",
        "catalogue.page",
        "action.invoke",
        "action.result",
        "value.set",
        "value.state",
        "focus.changed",
        "timezone.changed",
        "now_playing",
        "system_metrics",
        "artwork.begin",
        "artwork.ack",
        "artwork.end",
        "artwork.abort",
        "artwork.request",
        "app_icon.request",
        "app_icon.begin",
        "app_icon.unchanged",
        "app_icon.unavailable",
        "app_icon.ack",
        "app_icon.end",
        "app_icon.abort",
        "error",
        "catalogue.definitions.page",
        "focus.targets",
    ]
    static let cardModes: [String: String] = [
        "app": "Applications",
        "shortcut": "Keyboard shortcut",
        "url": "Open URL",
        "folder": "Open folder",
        "stats": "Stats",
        "window": "Window control",
        "webapp": "Web App",
    ]
    static let windowActions: [String: CompanionWindowActionCapability] = [
        "window.close": .init(key: "w", flags: [.maskCommand], minimumMacOS: 13, menuPaths: []),
        "window.minimize": .init(key: "m", flags: [.maskCommand], minimumMacOS: 13, menuPaths: []),
        "window.hide": .init(key: "h", flags: [.maskCommand], minimumMacOS: 13, menuPaths: []),
        "window.fullscreen": .init(key: "f", flags: [.maskControl, .maskCommand], minimumMacOS: 13, menuPaths: []),
        "window.fill": .init(key: "f", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15, menuPaths: []),
        "window.center": .init(key: "c", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15, menuPaths: []),
        "window.left": .init(key: "left", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15, menuPaths: []),
        "window.right": .init(key: "right", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15, menuPaths: []),
        "window.top": .init(key: "up", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15, menuPaths: []),
        "window.bottom": .init(key: "down", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15, menuPaths: []),
        "window.top-left": .init(key: nil, flags: [], minimumMacOS: 15, menuPaths: []),
        "window.top-right": .init(key: nil, flags: [], minimumMacOS: 15, menuPaths: []),
        "window.bottom-left": .init(key: nil, flags: [], minimumMacOS: 15, menuPaths: []),
        "window.bottom-right": .init(key: nil, flags: [], minimumMacOS: 15, menuPaths: []),
        "window.restore": .init(key: "r", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15, menuPaths: []),
        "window.arrange.left-right": .init(key: "left", flags: [.maskSecondaryFn, .maskControl, .maskShift], minimumMacOS: 15, menuPaths: []),
        "window.arrange.right-left": .init(key: "right", flags: [.maskSecondaryFn, .maskControl, .maskShift], minimumMacOS: 15, menuPaths: []),
        "window.arrange.top-bottom": .init(key: "up", flags: [.maskSecondaryFn, .maskControl, .maskShift], minimumMacOS: 15, menuPaths: []),
        "window.arrange.bottom-top": .init(key: "down", flags: [.maskSecondaryFn, .maskControl, .maskShift], minimumMacOS: 15, menuPaths: []),
        "window.arrange.left-quarters": .init(key: "left", flags: [.maskSecondaryFn, .maskControl, .maskAlternate, .maskShift], minimumMacOS: 15, menuPaths: []),
        "window.arrange.right-quarters": .init(key: "right", flags: [.maskSecondaryFn, .maskControl, .maskAlternate, .maskShift], minimumMacOS: 15, menuPaths: []),
        "window.arrange.top-quarters": .init(key: "up", flags: [.maskSecondaryFn, .maskControl, .maskAlternate, .maskShift], minimumMacOS: 15, menuPaths: []),
        "window.arrange.bottom-quarters": .init(key: "down", flags: [.maskSecondaryFn, .maskControl, .maskAlternate, .maskShift], minimumMacOS: 15, menuPaths: []),
        "window.arrange.quarters": .init(key: nil, flags: [], minimumMacOS: 15, menuPaths: []),
        "window.fullscreen.enter": .init(key: nil, flags: [], minimumMacOS: 15, menuPaths: []),
        "window.fullscreen.exit": .init(key: nil, flags: [], minimumMacOS: 15, menuPaths: []),
        "window.split.left": .init(key: nil, flags: [], minimumMacOS: 15, menuPaths: [["Window", "Full Screen Tile", "Left of Screen"], ["Window", "Full-Screen Tile", "Left of Screen"]]),
        "window.split.right": .init(key: nil, flags: [], minimumMacOS: 15, menuPaths: [["Window", "Full Screen Tile", "Right of Screen"], ["Window", "Full-Screen Tile", "Right of Screen"]]),
    ]
}
