#pragma once
// Generated by scripts/build.py companion from product/v2/app_shortcuts/*.json. Do not edit.
#include <string>
namespace companion_shortcut_catalog {
inline const char *app_label(const std::string &app) {
  if (app == "com.openai.codex") return "Codex";
  if (app == "com.apple.Safari") return "Safari";
  if (app == "com.tinyspeck.slackmacgap") return "Slack";
  return "";
}
inline bool has_shortcut(const std::string &app, const std::string &id) {
  if (app == "com.openai.codex") return id == "0" || id == "1" || id == "2" || id == "3" || id == "4" || id == "5" || id == "6";
  if (app == "com.apple.Safari") return id == "0" || id == "1" || id == "2" || id == "3" || id == "4";
  if (app == "com.tinyspeck.slackmacgap") return id == "0" || id == "1" || id == "2" || id == "3" || id == "4";
  return false;
}
}  // namespace companion_shortcut_catalog
