#pragma once
#include <cstdint>
#include <string>
// Generated by scripts/build.py; edit product/v2/cards instead.
constexpr int CARD_CONTRACT_VERSION = 1;
namespace espdesktop::card_runtime {

enum class CardTypeId : uint8_t {
  CALENDAR,
  CLOCK,
  COMPANION,
  SCREEN_LOCK,
  WEBHOOK,
  SUBPAGE,
  TIMEZONE,
  UNKNOWN,
};

enum class CardDriverId : uint8_t {
  DATE_TIME,
  COMPANION,
  SCREEN_LOCK,
  WEBHOOK,
  SUBPAGE,
  UNKNOWN,
};

enum CardCapabilityFlag : uint16_t {
  CAPABILITY_NONE = 0,
  CAPABILITY_INFORMATION_ONLY = 1u << 0,
  CAPABILITY_SUBSCRIPTIONS = 1u << 1,
  CAPABILITY_ACTIONS = 1u << 2,
  CAPABILITY_NUMERIC_CONTROL = 1u << 3,
  CAPABILITY_MODAL = 1u << 4,
  CAPABILITY_RUNTIME_ALLOCATION = 1u << 5,
  CAPABILITY_SUBPAGE = 1u << 6,
};

struct CardRuntimeSpec {
  CardTypeId type = CardTypeId::UNKNOWN;
  CardDriverId driver = CardDriverId::UNKNOWN;
  uint16_t capabilities = CAPABILITY_NONE;
};

constexpr bool has_capability(const CardRuntimeSpec &spec, CardCapabilityFlag capability) {
  return (spec.capabilities & static_cast<uint16_t>(capability)) != 0;
}

inline CardTypeId card_type_id(const std::string &type) {
  if (type == "calendar") return CardTypeId::CALENDAR;
  if (type == "clock") return CardTypeId::CLOCK;
  if (type == "companion") return CardTypeId::COMPANION;
  if (type == "screen_lock") return CardTypeId::SCREEN_LOCK;
  if (type == "webhook") return CardTypeId::WEBHOOK;
  if (type == "subpage") return CardTypeId::SUBPAGE;
  if (type == "timezone") return CardTypeId::TIMEZONE;
  return CardTypeId::UNKNOWN;
}

inline CardRuntimeSpec card_runtime_spec(CardTypeId type) {
  switch (type) {
    case CardTypeId::CALENDAR: return {type, CardDriverId::DATE_TIME, static_cast<uint16_t>(CAPABILITY_INFORMATION_ONLY | CAPABILITY_SUBPAGE)};
    case CardTypeId::CLOCK: return {type, CardDriverId::DATE_TIME, static_cast<uint16_t>(CAPABILITY_INFORMATION_ONLY | CAPABILITY_SUBPAGE)};
    case CardTypeId::COMPANION: return {type, CardDriverId::COMPANION, static_cast<uint16_t>(CAPABILITY_ACTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::SCREEN_LOCK: return {type, CardDriverId::SCREEN_LOCK, static_cast<uint16_t>(CAPABILITY_ACTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::WEBHOOK: return {type, CardDriverId::WEBHOOK, static_cast<uint16_t>(CAPABILITY_ACTIONS | CAPABILITY_SUBPAGE)};
    case CardTypeId::SUBPAGE: return {type, CardDriverId::SUBPAGE, static_cast<uint16_t>(CAPABILITY_ACTIONS | CAPABILITY_RUNTIME_ALLOCATION)};
    case CardTypeId::TIMEZONE: return {type, CardDriverId::DATE_TIME, static_cast<uint16_t>(CAPABILITY_INFORMATION_ONLY | CAPABILITY_SUBPAGE)};
    default: return {};
  }
}

inline CardDriverId resolve_card_driver(CardTypeId type, const std::string &mode) {
  switch (type) {
    default: return card_runtime_spec(type).driver;
  }
}

template<typename Config>
inline CardRuntimeSpec resolve_card_runtime(const Config &config) {
  CardRuntimeSpec spec = card_runtime_spec(card_type_id(config.type));
  switch (spec.type) {
    default:
      break;
  }
  return spec;
}

}  // namespace espdesktop::card_runtime

inline const char *card_contract_card_label(const std::string &type) {
  if (type == "calendar") return "Date & Time";
  if (type == "clock") return "Date & Time";
  if (type == "companion") return "Companion";
  if (type == "screen_lock") return "Screen Lock";
  if (type == "webhook") return "Webhook";
  if (type == "subpage") return "Subpage";
  if (type == "timezone") return "Date & Time";
  return "";
}
inline const char *card_contract_default_icon_name(const std::string &type) {
  if (type == "calendar") return "Auto";
  if (type == "clock") return "Auto";
  if (type == "companion") return "Monitor";
  if (type == "screen_lock") return "Lock";
  if (type == "webhook") return "Auto";
  if (type == "subpage") return "Auto";
  if (type == "timezone") return "Auto";
  return "Auto";
}
inline const char *card_contract_default_icon_on_name(const std::string &type) {
  if (type == "calendar") return "Auto";
  if (type == "clock") return "Auto";
  if (type == "companion") return "Auto";
  if (type == "screen_lock") return "Lock Open";
  if (type == "webhook") return "Auto";
  if (type == "subpage") return "Auto";
  if (type == "timezone") return "Auto";
  return "Auto";
}
inline const char *card_contract_subpage_type_from_code(const std::string &code) {
  if (code == "D") return "calendar";
  if (code == "CK") return "clock";
  if (code == "T") return "timezone";
  if (code == "CP") return "companion";
  if (code == "SL") return "screen_lock";
  if (code == "WH") return "webhook";
  if (code == "G") return "subpage";
  return "";
}
inline bool card_contract_allow_in_subpage(const std::string &type) {
  return type == "calendar" || type == "clock" || type == "companion" || type == "screen_lock" || type == "webhook" || type == "timezone";
}
constexpr const char *CARD_CONTRACT_OPTION_NAME_APP_SHORTCUT_PRESET = "app_shortcut_preset";
constexpr const char *CARD_CONTRACT_OPTION_NAME_APP_SHORTCUTS = "app_shortcuts";
constexpr const char *CARD_CONTRACT_OPTION_NAME_APP_SHORTCUTS_AUTO_SWITCH = "app_shortcuts_auto_switch";
constexpr const char *CARD_CONTRACT_OPTION_NAME_APP_SHORTCUTS_TABS = "app_shortcuts_tabs";
constexpr const char *CARD_CONTRACT_OPTION_NAME_DATE_TIME_MODE = "date_time_mode";
constexpr const char *CARD_CONTRACT_OPTION_NAME_LARGE_NUMBERS = "large_numbers";
constexpr const char *CARD_CONTRACT_OPTION_NAME_SUBPAGE_CONNECTOR = "subpage_connector";
constexpr const char *CARD_CONTRACT_OPTION_NAME_SUBPAGE_KIND = "subpage_kind";
constexpr const char *CARD_CONTRACT_OPTION_NAME_WEBHOOK_HEADERS = "webhook_headers";
