#pragma once
// GENERATED by scripts/build.py companion. Do not edit.
#include <ArduinoJson.h>
#include <cmath>
#include <cstring>
#include <optional>
#include <string>
#include <variant>
#include <vector>
#include "companion_capabilities_generated.h"

namespace companion_protocol {
using namespace ArduinoJson;
enum class SessionState { PAIRING, AUTHENTICATING, CONNECTED };
enum class Direction { PANEL_TO_MAC, MAC_TO_PANEL };
inline bool string_valid(JsonVariantConst value, size_t minimum, size_t maximum) {
  if (!value.is<const char *>()) return false;
  const auto text = value.as<JsonString>();
  return text.size() >= minimum && text.size() <= maximum &&
         std::strlen(text.c_str()) == text.size();
}
inline bool number_valid(JsonVariantConst value, double minimum, double maximum, bool integer) {
  if (value.is<bool>() || !value.is<double>()) return false;
  const double n = value.as<double>();
  return std::isfinite(n) && n >= minimum && n <= maximum && (!integer || std::floor(n) == n);
}
inline bool hex_valid(JsonVariantConst value) {
  if (!string_valid(value, 64, 64)) return false;
  for (const char *c = value.as<const char *>(); *c; ++c)
    if (!(*c >= '0' && *c <= '9') && !(*c >= 'a' && *c <= 'f') && !(*c >= 'A' && *c <= 'F')) return false;
  return true;
}
struct Hello {

};
struct PairRequest {
  std::string code{};
};
struct PairAccepted {
  std::string credential{};
};
struct AuthRequest {
  uint32_t sequence{};
  std::string nonce{};
  std::string signature{};
};
struct AuthAccepted {
  uint32_t capabilityVersion{};
};
struct Capabilities {
  std::vector<std::string> values{};
};
struct CatalogueRequest {

};
struct CataloguePageItemsItem {
  std::string id{};
  std::string label{};
};
struct CataloguePage {
  uint32_t generation{};
  uint32_t page{};
  bool complete{};
  std::vector<CataloguePageItemsItem> items{};
};
struct ActionInvoke {
  std::string requestId{};
  std::string kind{};
  std::optional<std::string> actionId{};
  std::optional<std::string> appId{};
  std::optional<std::string> encodedUrl{};
};
struct ActionResult {
  std::string requestId{};
  std::string status{};
};
struct ValueSet {
  std::string requestId{};
  std::string controlId{};
  uint32_t value{};
};
struct ValueState {
  std::string controlId{};
  bool available{};
  std::optional<uint32_t> value{};
};
struct FocusChanged {
  std::string actionId{};
};
struct TimezoneChanged {
  std::string identifier{};
};
struct NowPlaying {
  uint32_t generation{};
  std::string applicationIdentifier{};
  std::string applicationName{};
  std::string contentIdentifier{};
  std::string title{};
  std::string artist{};
  std::string album{};
  std::string state{};
  double durationMs{};
  double positionMs{};
  double playbackRate{};
  bool hasArtwork{};
  std::optional<std::string> artworkSHA256{};
};
struct SystemMetrics {
  uint32_t generation{};
  std::optional<bool> available{};
  std::optional<double> cpuUsagePercent{};
  std::optional<double> memoryUsagePercent{};
  std::optional<double> storageUsagePercent{};
  std::optional<double> batteryPercent{};
  std::optional<double> networkThroughputKBps{};
};
struct ArtworkBegin {
  uint32_t generation{};
  uint32_t byteLength{};
  std::string sha256{};
  std::string mimeType{};
};
struct ArtworkAck {
  uint32_t generation{};
  uint32_t nextOffset{};
};
struct ArtworkEnd {
  uint32_t generation{};
};
struct ArtworkAbort {
  uint32_t generation{};
};
struct ArtworkRequest {
  uint32_t generation{};
};
struct Error {
  std::string code{};
  std::optional<uint32_t> lastSequence{};
};
inline void encode(JsonObject root, const Hello &message) {
  root["type"] = "hello";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  (void) message;
}
inline void encode(JsonObject root, const PairRequest &message) {
  root["type"] = "pair.request";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["code"] = message.code;
}
inline void encode(JsonObject root, const PairAccepted &message) {
  root["type"] = "pair.accepted";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["credential"] = message.credential;
}
inline void encode(JsonObject root, const AuthRequest &message) {
  root["type"] = "auth.request";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["sequence"] = message.sequence;
  root["nonce"] = message.nonce;
  root["signature"] = message.signature;
}
inline void encode(JsonObject root, const AuthAccepted &message) {
  root["type"] = "auth.accepted";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["capabilityVersion"] = message.capabilityVersion;
}
inline void encode(JsonObject root, const Capabilities &message) {
  root["type"] = "capabilities";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  auto values_values = root["values"].to<JsonArray>();
  for (const auto &item : message.values) {
    values_values.add(item);
  }
}
inline void encode(JsonObject root, const CatalogueRequest &message) {
  root["type"] = "catalogue.request";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  (void) message;
}
inline void encode(JsonObject root, const CataloguePage &message) {
  root["type"] = "catalogue.page";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["generation"] = message.generation;
  root["page"] = message.page;
  root["complete"] = message.complete;
  auto values_items = root["items"].to<JsonArray>();
  for (const auto &item : message.items) {
    auto entry = values_items.add<JsonObject>();
    entry["id"] = item.id;
    entry["label"] = item.label;
  }
}
inline void encode(JsonObject root, const ActionInvoke &message) {
  root["type"] = "action.invoke";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["requestId"] = message.requestId;
  root["kind"] = message.kind;
  if (message.actionId) root["actionId"] = *message.actionId;
  if (message.appId) root["appId"] = *message.appId;
  if (message.encodedUrl) root["encodedUrl"] = *message.encodedUrl;
}
inline void encode(JsonObject root, const ActionResult &message) {
  root["type"] = "action.result";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["requestId"] = message.requestId;
  root["status"] = message.status;
}
inline void encode(JsonObject root, const ValueSet &message) {
  root["type"] = "value.set";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["requestId"] = message.requestId;
  root["controlId"] = message.controlId;
  root["value"] = message.value;
}
inline void encode(JsonObject root, const ValueState &message) {
  root["type"] = "value.state";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["controlId"] = message.controlId;
  root["available"] = message.available;
  if (message.value) root["value"] = *message.value;
}
inline void encode(JsonObject root, const FocusChanged &message) {
  root["type"] = "focus.changed";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["actionId"] = message.actionId;
}
inline void encode(JsonObject root, const TimezoneChanged &message) {
  root["type"] = "timezone.changed";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["identifier"] = message.identifier;
}
inline void encode(JsonObject root, const NowPlaying &message) {
  root["type"] = "now_playing";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["generation"] = message.generation;
  root["applicationIdentifier"] = message.applicationIdentifier;
  root["applicationName"] = message.applicationName;
  root["contentIdentifier"] = message.contentIdentifier;
  root["title"] = message.title;
  root["artist"] = message.artist;
  root["album"] = message.album;
  root["state"] = message.state;
  root["durationMs"] = message.durationMs;
  root["positionMs"] = message.positionMs;
  root["playbackRate"] = message.playbackRate;
  root["hasArtwork"] = message.hasArtwork;
  if (message.artworkSHA256) root["artworkSHA256"] = *message.artworkSHA256;
}
inline void encode(JsonObject root, const SystemMetrics &message) {
  root["type"] = "system_metrics";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["generation"] = message.generation;
  if (message.available) root["available"] = *message.available;
  if (message.cpuUsagePercent) root["cpuUsagePercent"] = *message.cpuUsagePercent;
  if (message.memoryUsagePercent) root["memoryUsagePercent"] = *message.memoryUsagePercent;
  if (message.storageUsagePercent) root["storageUsagePercent"] = *message.storageUsagePercent;
  if (message.batteryPercent) root["batteryPercent"] = *message.batteryPercent;
  if (message.networkThroughputKBps) root["networkThroughputKBps"] = *message.networkThroughputKBps;
}
inline void encode(JsonObject root, const ArtworkBegin &message) {
  root["type"] = "artwork.begin";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["generation"] = message.generation;
  root["byteLength"] = message.byteLength;
  root["sha256"] = message.sha256;
  root["mimeType"] = message.mimeType;
}
inline void encode(JsonObject root, const ArtworkAck &message) {
  root["type"] = "artwork.ack";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["generation"] = message.generation;
  root["nextOffset"] = message.nextOffset;
}
inline void encode(JsonObject root, const ArtworkEnd &message) {
  root["type"] = "artwork.end";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["generation"] = message.generation;
}
inline void encode(JsonObject root, const ArtworkAbort &message) {
  root["type"] = "artwork.abort";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["generation"] = message.generation;
}
inline void encode(JsonObject root, const ArtworkRequest &message) {
  root["type"] = "artwork.request";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["generation"] = message.generation;
}
inline void encode(JsonObject root, const Error &message) {
  root["type"] = "error";
  root["protocol"] = COMPANION_PROTOCOL_VERSION;
  root["code"] = message.code;
  if (message.lastSequence) root["lastSequence"] = *message.lastSequence;
}
using Message = std::variant<Hello, PairRequest, PairAccepted, AuthRequest, AuthAccepted, Capabilities, CatalogueRequest, CataloguePage, ActionInvoke, ActionResult, ValueSet, ValueState, FocusChanged, TimezoneChanged, NowPlaying, SystemMetrics, ArtworkBegin, ArtworkAck, ArtworkEnd, ArtworkAbort, ArtworkRequest, Error>;
inline std::optional<Message> decode(JsonObjectConst root, Direction direction, SessionState state) {
  if (!number_valid(root["protocol"], COMPANION_PROTOCOL_VERSION, COMPANION_PROTOCOL_VERSION, true) || !root["type"].is<const char *>()) return std::nullopt;
  const std::string type = root["type"].as<std::string>();
  if (type == "hello") {
    if (direction != Direction::PANEL_TO_MAC) return std::nullopt;
    if (!(state == SessionState::PAIRING || state == SessionState::AUTHENTICATING || state == SessionState::CONNECTED)) return std::nullopt;

    Hello result;
    return result;
  }
  if (type == "pair.request") {
    if (direction != Direction::MAC_TO_PANEL) return std::nullopt;
    if (!(state == SessionState::PAIRING)) return std::nullopt;
    {
      if (!(string_valid(root["code"], 1, 16))) return std::nullopt;
    }
    PairRequest result;
    result.code = root["code"].as<std::string>();
    return result;
  }
  if (type == "pair.accepted") {
    if (direction != Direction::PANEL_TO_MAC) return std::nullopt;
    if (!(state == SessionState::PAIRING)) return std::nullopt;
    {
      if (!(string_valid(root["credential"], 1, 64) && hex_valid(root["credential"]))) return std::nullopt;
    }
    PairAccepted result;
    result.credential = root["credential"].as<std::string>();
    return result;
  }
  if (type == "auth.request") {
    if (direction != Direction::MAC_TO_PANEL) return std::nullopt;
    if (!(state == SessionState::AUTHENTICATING)) return std::nullopt;
    {
      if (!(number_valid(root["sequence"], 1, 4294967295, true))) return std::nullopt;
    }
    {
      if (!(string_valid(root["nonce"], 1, 96))) return std::nullopt;
    }
    {
      if (!(string_valid(root["signature"], 1, 64) && hex_valid(root["signature"]))) return std::nullopt;
    }
    AuthRequest result;
    result.sequence = root["sequence"].as<uint32_t>();
    result.nonce = root["nonce"].as<std::string>();
    result.signature = root["signature"].as<std::string>();
    return result;
  }
  if (type == "auth.accepted") {
    if (direction != Direction::PANEL_TO_MAC) return std::nullopt;
    if (!(state == SessionState::AUTHENTICATING)) return std::nullopt;
    {
      if (!(number_valid(root["capabilityVersion"], 1, 4294967295, true))) return std::nullopt;
    }
    AuthAccepted result;
    result.capabilityVersion = root["capabilityVersion"].as<uint32_t>();
    return result;
  }
  if (type == "capabilities") {
    if (direction != Direction::MAC_TO_PANEL) return std::nullopt;
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(root["values"].is<JsonArrayConst>() && root["values"].size() <= 64)) return std::nullopt;
      for (JsonVariantConst item : root["values"].as<JsonArrayConst>()) {
        if (!(string_valid(item, 1, 96))) return std::nullopt;
      }
    }
    Capabilities result;
    for (JsonVariantConst item : root["values"].as<JsonArrayConst>()) {
      result.values.push_back(item.as<std::string>());
    }
    return result;
  }
  if (type == "catalogue.request") {
    if (direction != Direction::PANEL_TO_MAC) return std::nullopt;
    if (!(state == SessionState::CONNECTED)) return std::nullopt;

    CatalogueRequest result;
    return result;
  }
  if (type == "catalogue.page") {
    if (direction != Direction::MAC_TO_PANEL) return std::nullopt;
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(number_valid(root["generation"], 1, 4294967295, true))) return std::nullopt;
    }
    {
      if (!(number_valid(root["page"], 0, 65535, true))) return std::nullopt;
    }
    {
      if (!(root["complete"].is<bool>())) return std::nullopt;
    }
    {
      if (!(root["items"].is<JsonArrayConst>() && root["items"].size() <= 48)) return std::nullopt;
      for (JsonVariantConst item : root["items"].as<JsonArrayConst>()) {
        if (!(item.is<JsonObjectConst>())) return std::nullopt;
        {
          if (!(string_valid(item.as<JsonObjectConst>()["id"], 1, 96))) return std::nullopt;
        }
        {
          if (!(string_valid(item.as<JsonObjectConst>()["label"], 1, 96))) return std::nullopt;
        }
      }
    }
    CataloguePage result;
    result.generation = root["generation"].as<uint32_t>();
    result.page = root["page"].as<uint32_t>();
    result.complete = root["complete"].as<bool>();
    for (JsonVariantConst item : root["items"].as<JsonArrayConst>()) {
      result.items.push_back({item["id"].as<std::string>(), item["label"].as<std::string>()});
    }
    return result;
  }
  if (type == "action.invoke") {
    if (direction != Direction::PANEL_TO_MAC) return std::nullopt;
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(string_valid(root["requestId"], 1, 64))) return std::nullopt;
    }
    {
      if (!(string_valid(root["kind"], 1, 6) && (root["kind"].as<std::string>() == "action" || root["kind"].as<std::string>() == "url"))) return std::nullopt;
    }
    if (!root["actionId"].isUnbound()) {
      if (!(string_valid(root["actionId"], 1, 96))) return std::nullopt;
    }
    if (!root["appId"].isUnbound()) {
      if (!(string_valid(root["appId"], 1, 96))) return std::nullopt;
    }
    if (!root["encodedUrl"].isUnbound()) {
      if (!(string_valid(root["encodedUrl"], 1, 128))) return std::nullopt;
    }
    if (root["kind"].as<std::string>() == "action") {
      if (!!root["actionId"].isUnbound()) return std::nullopt;
    }
    if (root["kind"].as<std::string>() == "url") {
      if (!!root["appId"].isUnbound()) return std::nullopt;
      if (!!root["encodedUrl"].isUnbound()) return std::nullopt;
    }
    ActionInvoke result;
    result.requestId = root["requestId"].as<std::string>();
    result.kind = root["kind"].as<std::string>();
    if (!root["actionId"].isUnbound()) result.actionId = root["actionId"].as<std::string>();
    if (!root["appId"].isUnbound()) result.appId = root["appId"].as<std::string>();
    if (!root["encodedUrl"].isUnbound()) result.encodedUrl = root["encodedUrl"].as<std::string>();
    return result;
  }
  if (type == "action.result") {
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(string_valid(root["requestId"], 1, 64))) return std::nullopt;
    }
    {
      if (!(string_valid(root["status"], 1, 11) && (root["status"].as<std::string>() == "activated" || root["status"].as<std::string>() == "performed" || root["status"].as<std::string>() == "opened" || root["status"].as<std::string>() == "not_allowed" || root["status"].as<std::string>() == "not_found" || root["status"].as<std::string>() == "failed"))) return std::nullopt;
    }
    ActionResult result;
    result.requestId = root["requestId"].as<std::string>();
    result.status = root["status"].as<std::string>();
    return result;
  }
  if (type == "value.set") {
    if (direction != Direction::PANEL_TO_MAC) return std::nullopt;
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(string_valid(root["requestId"], 1, 64))) return std::nullopt;
    }
    {
      if (!(string_valid(root["controlId"], 1, 19) && (root["controlId"].as<std::string>() == "media.output_volume" || root["controlId"].as<std::string>() == "media.input_volume"))) return std::nullopt;
    }
    {
      if (!(number_valid(root["value"], 0, 100, true))) return std::nullopt;
    }
    ValueSet result;
    result.requestId = root["requestId"].as<std::string>();
    result.controlId = root["controlId"].as<std::string>();
    result.value = root["value"].as<uint32_t>();
    return result;
  }
  if (type == "value.state") {
    if (direction != Direction::MAC_TO_PANEL) return std::nullopt;
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(string_valid(root["controlId"], 1, 19) && (root["controlId"].as<std::string>() == "media.output_volume" || root["controlId"].as<std::string>() == "media.input_volume"))) return std::nullopt;
    }
    {
      if (!(root["available"].is<bool>())) return std::nullopt;
    }
    if (!root["value"].isUnbound()) {
      if (!(number_valid(root["value"], 0, 100, true))) return std::nullopt;
    }
    if (root["available"].as<bool>() == true) {
      if (!!root["value"].isUnbound()) return std::nullopt;
    }
    ValueState result;
    result.controlId = root["controlId"].as<std::string>();
    result.available = root["available"].as<bool>();
    if (!root["value"].isUnbound()) result.value = root["value"].as<uint32_t>();
    return result;
  }
  if (type == "focus.changed") {
    if (direction != Direction::MAC_TO_PANEL) return std::nullopt;
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(string_valid(root["actionId"], 0, 96))) return std::nullopt;
    }
    FocusChanged result;
    result.actionId = root["actionId"].as<std::string>();
    return result;
  }
  if (type == "timezone.changed") {
    if (direction != Direction::MAC_TO_PANEL) return std::nullopt;
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(string_valid(root["identifier"], 1, 96))) return std::nullopt;
    }
    TimezoneChanged result;
    result.identifier = root["identifier"].as<std::string>();
    return result;
  }
  if (type == "now_playing") {
    if (direction != Direction::MAC_TO_PANEL) return std::nullopt;
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(number_valid(root["generation"], 1, 4294967295, true))) return std::nullopt;
    }
    {
      if (!(string_valid(root["applicationIdentifier"], 0, 256))) return std::nullopt;
    }
    {
      if (!(string_valid(root["applicationName"], 0, 256))) return std::nullopt;
    }
    {
      if (!(string_valid(root["contentIdentifier"], 0, 256))) return std::nullopt;
    }
    {
      if (!(string_valid(root["title"], 0, 256))) return std::nullopt;
    }
    {
      if (!(string_valid(root["artist"], 0, 256))) return std::nullopt;
    }
    {
      if (!(string_valid(root["album"], 0, 256))) return std::nullopt;
    }
    {
      if (!(string_valid(root["state"], 1, 11) && (root["state"].as<std::string>() == "playing" || root["state"].as<std::string>() == "paused" || root["state"].as<std::string>() == "stopped" || root["state"].as<std::string>() == "unavailable"))) return std::nullopt;
    }
    {
      if (!(number_valid(root["durationMs"], 0, 86400000, false))) return std::nullopt;
    }
    {
      if (!(number_valid(root["positionMs"], 0, 86400000, false))) return std::nullopt;
    }
    {
      if (!(number_valid(root["playbackRate"], -16, 16, false))) return std::nullopt;
    }
    {
      if (!(root["hasArtwork"].is<bool>())) return std::nullopt;
    }
    if (!root["artworkSHA256"].isUnbound()) {
      if (!(string_valid(root["artworkSHA256"], 1, 64) && hex_valid(root["artworkSHA256"]))) return std::nullopt;
    }
    NowPlaying result;
    result.generation = root["generation"].as<uint32_t>();
    result.applicationIdentifier = root["applicationIdentifier"].as<std::string>();
    result.applicationName = root["applicationName"].as<std::string>();
    result.contentIdentifier = root["contentIdentifier"].as<std::string>();
    result.title = root["title"].as<std::string>();
    result.artist = root["artist"].as<std::string>();
    result.album = root["album"].as<std::string>();
    result.state = root["state"].as<std::string>();
    result.durationMs = root["durationMs"].as<double>();
    result.positionMs = root["positionMs"].as<double>();
    result.playbackRate = root["playbackRate"].as<double>();
    result.hasArtwork = root["hasArtwork"].as<bool>();
    if (!root["artworkSHA256"].isUnbound()) result.artworkSHA256 = root["artworkSHA256"].as<std::string>();
    return result;
  }
  if (type == "system_metrics") {
    if (direction != Direction::MAC_TO_PANEL) return std::nullopt;
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(number_valid(root["generation"], 1, 4294967295, true))) return std::nullopt;
    }
    if (!root["available"].isUnbound()) {
      if (!(root["available"].is<bool>())) return std::nullopt;
    }
    if (!root["cpuUsagePercent"].isUnbound()) {
      if (!(number_valid(root["cpuUsagePercent"], 0, 100, false))) return std::nullopt;
    }
    if (!root["memoryUsagePercent"].isUnbound()) {
      if (!(number_valid(root["memoryUsagePercent"], 0, 100, false))) return std::nullopt;
    }
    if (!root["storageUsagePercent"].isUnbound()) {
      if (!(number_valid(root["storageUsagePercent"], 0, 100, false))) return std::nullopt;
    }
    if (!root["batteryPercent"].isUnbound()) {
      if (!(number_valid(root["batteryPercent"], 0, 100, false))) return std::nullopt;
    }
    if (!root["networkThroughputKBps"].isUnbound()) {
      if (!(number_valid(root["networkThroughputKBps"], 0, 1000000000.0, false))) return std::nullopt;
    }
    if ((!!root["available"].isUnbound() || root["available"].as<bool>() != false)) {
      if (!!root["cpuUsagePercent"].isUnbound()) return std::nullopt;
      if (!!root["memoryUsagePercent"].isUnbound()) return std::nullopt;
      if (!!root["storageUsagePercent"].isUnbound()) return std::nullopt;
    }
    SystemMetrics result;
    result.generation = root["generation"].as<uint32_t>();
    if (!root["available"].isUnbound()) result.available = root["available"].as<bool>();
    if (!root["cpuUsagePercent"].isUnbound()) result.cpuUsagePercent = root["cpuUsagePercent"].as<double>();
    if (!root["memoryUsagePercent"].isUnbound()) result.memoryUsagePercent = root["memoryUsagePercent"].as<double>();
    if (!root["storageUsagePercent"].isUnbound()) result.storageUsagePercent = root["storageUsagePercent"].as<double>();
    if (!root["batteryPercent"].isUnbound()) result.batteryPercent = root["batteryPercent"].as<double>();
    if (!root["networkThroughputKBps"].isUnbound()) result.networkThroughputKBps = root["networkThroughputKBps"].as<double>();
    return result;
  }
  if (type == "artwork.begin") {
    if (direction != Direction::MAC_TO_PANEL) return std::nullopt;
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(number_valid(root["generation"], 1, 4294967295, true))) return std::nullopt;
    }
    {
      if (!(number_valid(root["byteLength"], 1, 262144, true))) return std::nullopt;
    }
    {
      if (!(string_valid(root["sha256"], 1, 64) && hex_valid(root["sha256"]))) return std::nullopt;
    }
    {
      if (!(string_valid(root["mimeType"], 1, 10) && (root["mimeType"].as<std::string>() == "image/jpeg"))) return std::nullopt;
    }
    ArtworkBegin result;
    result.generation = root["generation"].as<uint32_t>();
    result.byteLength = root["byteLength"].as<uint32_t>();
    result.sha256 = root["sha256"].as<std::string>();
    result.mimeType = root["mimeType"].as<std::string>();
    return result;
  }
  if (type == "artwork.ack") {
    if (direction != Direction::PANEL_TO_MAC) return std::nullopt;
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(number_valid(root["generation"], 1, 4294967295, true))) return std::nullopt;
    }
    {
      if (!(number_valid(root["nextOffset"], 0, 262144, true))) return std::nullopt;
    }
    ArtworkAck result;
    result.generation = root["generation"].as<uint32_t>();
    result.nextOffset = root["nextOffset"].as<uint32_t>();
    return result;
  }
  if (type == "artwork.end") {
    if (direction != Direction::MAC_TO_PANEL) return std::nullopt;
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(number_valid(root["generation"], 1, 4294967295, true))) return std::nullopt;
    }
    ArtworkEnd result;
    result.generation = root["generation"].as<uint32_t>();
    return result;
  }
  if (type == "artwork.abort") {
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(number_valid(root["generation"], 1, 4294967295, true))) return std::nullopt;
    }
    ArtworkAbort result;
    result.generation = root["generation"].as<uint32_t>();
    return result;
  }
  if (type == "artwork.request") {
    if (direction != Direction::PANEL_TO_MAC) return std::nullopt;
    if (!(state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(number_valid(root["generation"], 1, 4294967295, true))) return std::nullopt;
    }
    ArtworkRequest result;
    result.generation = root["generation"].as<uint32_t>();
    return result;
  }
  if (type == "error") {
    if (!(state == SessionState::PAIRING || state == SessionState::AUTHENTICATING || state == SessionState::CONNECTED)) return std::nullopt;
    {
      if (!(string_valid(root["code"], 1, 64))) return std::nullopt;
    }
    if (!root["lastSequence"].isUnbound()) {
      if (!(number_valid(root["lastSequence"], 0, 4294967295, true))) return std::nullopt;
    }
    Error result;
    result.code = root["code"].as<std::string>();
    if (!root["lastSequence"].isUnbound()) result.lastSequence = root["lastSequence"].as<uint32_t>();
    return result;
  }
  return std::nullopt;
}
}  // namespace companion_protocol
