#pragma once
// Generated by scripts/build.py companion from product/v2/web_apps/*.json. Do not edit.
#include <string>
namespace companion_web_app_catalog {
inline const char *icon_url(const std::string &id) {
  if (id == "google-docs") return "https://raw.githubusercontent.com/jtenniswood/espdesktop/main/product/v2/web_apps/icons/google-docs.png";
  return "";
}
}
