"""Generate Companion v3 payload types and strict decoders from its product contract."""
from __future__ import annotations
import json
import re


def name(value):
    return ''.join(part[:1].upper() + part[1:] for part in re.split(r'[._]', value))


def validate_contract(data):
    def field(spec):
        kind = spec['type']
        if kind not in {'string', 'integer', 'number', 'boolean', 'array', 'object'}:
            raise ValueError(f'Unsupported Companion field type: {kind}')
        if kind == 'string':
            assert 0 <= spec['minLength'] <= spec['maxLength'] <= 16384
        if kind in {'integer', 'number'}:
            assert spec['minimum'] <= spec['maximum']
        if kind == 'array':
            assert 0 < spec['maxItems'] <= 256
            field(spec['items'])
        if kind == 'object':
            for child in spec['fields'].values(): field(child)
    for message in data['protocol']['messages']:
        assert message['states'] and set(message['states']) <= {'pairing', 'authenticating', 'connected'}
        for spec in message['fields'].values(): field(spec)
        for rule in message.get('requiresWhen', []):
            assert rule['field'] in message['fields']
            assert all(key in message['fields'] for key in rule['required'])


def cpp(data):
    out = ['''#pragma once
// GENERATED by scripts/build.py companion. Do not edit.
#include <ArduinoJson.h>
#include <cmath>
#include <cstring>
#include <optional>
#include <string>
#include <variant>
#include <vector>
#include "companion_capabilities_generated.h"

namespace companion_protocol {
using namespace ArduinoJson;
enum class SessionState { PAIRING, AUTHENTICATING, CONNECTED };
enum class Direction { PANEL_TO_MAC, MAC_TO_PANEL };
inline bool string_valid(JsonVariantConst value, size_t minimum, size_t maximum) {
  if (!value.is<const char *>()) return false;
  const auto text = value.as<JsonString>();
  return text.size() >= minimum && text.size() <= maximum &&
         std::strlen(text.c_str()) == text.size();
}
inline bool number_valid(JsonVariantConst value, double minimum, double maximum, bool integer) {
  if (value.is<bool>() || !value.is<double>()) return false;
  const double n = value.as<double>();
  return std::isfinite(n) && n >= minimum && n <= maximum && (!integer || std::floor(n) == n);
}
inline bool hex_valid(JsonVariantConst value) {
  if (!string_valid(value, 64, 64)) return false;
  for (const char *c = value.as<const char *>(); *c; ++c)
    if (!(*c >= '0' && *c <= '9') && !(*c >= 'a' && *c <= 'f') && !(*c >= 'A' && *c <= 'F')) return false;
  return true;
}
''']
    def type_for(spec, ident):
        kind = spec['type']
        if kind == 'object':
            struct(ident, spec['fields'])
            return ident
        if kind == 'array': return 'std::vector<' + type_for(spec['items'], ident + 'Item') + '>'
        return {'string':'std::string','integer':'uint32_t','number':'double','boolean':'bool'}[kind]
    def expr(spec, value):
        kind=spec['type']
        if kind=='string':
            e=f'string_valid({value}, {spec["minLength"]}, {spec["maxLength"]})'
            if 'enum' in spec: e+=' && ('+' || '.join(f'{value}.as<std::string>() == {json.dumps(v)}' for v in spec['enum'])+')'
            if spec.get('pattern')=='hex64': e+=f' && hex_valid({value})'
            return e
        if kind in ('number','integer'):
            return f'number_valid({value}, {spec["minimum"]}, {spec["maximum"]}, {str(kind=="integer").lower()})'
        if kind=='boolean':return f'{value}.is<bool>()'
        if kind=='array':return f'{value}.is<JsonArrayConst>() && {value}.size() <= {spec["maxItems"]}'
        return f'{value}.is<JsonObjectConst>()'
    def checks(fields, root, indent='  '):
        lines=[]
        for key,spec in fields.items():
            value=f'{root}[{json.dumps(key)}]'
            # Missing optional fields are allowed; explicit null is never a valid payload value.
            present=f'{root}.containsKey({json.dumps(key)})'
            lines.append(indent+f'if ({present}) {{' if spec.get('optional') else indent+'{')
            lines.append(indent+f'  if (!({expr(spec,value)})) return std::nullopt;')
            if spec['type']=='array':
                lines.append(indent+f'  for (JsonVariantConst item : {value}.as<JsonArrayConst>()) {{')
                lines.append(indent+f'    if (!({expr(spec["items"],"item")})) return std::nullopt;')
                if spec['items']['type']=='object':lines+=checks(spec['items']['fields'],'item.as<JsonObjectConst>()',indent+'    ')
                lines.append(indent+'  }')
            lines.append(indent+'}')
        return lines
    def struct(ident,fields):
        declarations=[]
        for key,spec in fields.items():
            typ=type_for(spec,ident+name(key))
            if spec.get('optional'):typ=f'std::optional<{typ}>'
            declarations.append(f'  {typ} {key}{{}};')
        out.append('struct '+ident+' {\n'+'\n'.join(declarations)+'\n};\n')
    def read(spec,value,ident):
        return value+'.as<'+{'string':'std::string','integer':'uint32_t','number':'double','boolean':'bool'}[spec['type']]+'>()'
    for m in data['protocol']['messages']:struct(name(m['id']),m['fields'])
    for m in data['protocol']['messages']:
        ident = name(m['id'])
        out.append(f'inline void encode(JsonObject root, const {ident} &message) {{\n')
        out.append(f'  root["type"] = {json.dumps(m["id"])};\n  root["protocol"] = COMPANION_PROTOCOL_VERSION;\n')
        if not m['fields']: out.append('  (void) message;\n')
        for key, spec in m['fields'].items():
            if spec['type'] == 'array':
                out.append(f'  auto values_{key} = root["{key}"].to<JsonArray>();\n')
                out.append(f'  for (const auto &item : message.{key}) {{\n')
                if spec['items']['type'] == 'object':
                    out.append(f'    auto entry = values_{key}.add<JsonObject>();\n')
                    for child in spec['items']['fields']:
                        out.append(f'    entry["{child}"] = item.{child};\n')
                else: out.append(f'    values_{key}.add(item);\n')
                out.append('  }\n')
            elif spec.get('optional'):
                out.append(f'  if (message.{key}) root["{key}"] = *message.{key};\n')
            else: out.append(f'  root["{key}"] = message.{key};\n')
        out.append('}\n')
    out.append('using Message = std::variant<'+', '.join(name(m['id']) for m in data['protocol']['messages'])+'>;\n')
    out.append('inline std::optional<Message> decode(JsonObjectConst root, Direction direction, SessionState state) {\n  if (!number_valid(root["protocol"], COMPANION_PROTOCOL_VERSION, COMPANION_PROTOCOL_VERSION, true) || !root["type"].is<const char *>()) return std::nullopt;\n  const std::string type = root["type"].as<std::string>();\n')
    for m in data['protocol']['messages']:
        ident=name(m['id']);out.append(f'  if (type == {json.dumps(m["id"])}) {{\n')
        if m['direction']!='bidirectional':out.append(f'    if (direction != Direction::{m["direction"].upper()}) return std::nullopt;\n')
        out.append('    if (!('+' || '.join('state == SessionState::'+s.upper() for s in m['states'])+')) return std::nullopt;\n')
        out.append('\n'.join(checks(m['fields'],'root','    '))+'\n')
        for rule in m.get('requiresWhen',[]):
            value=rule.get('equals',rule.get('unlessEquals'))
            cmp='!=' if 'unlessEquals' in rule else '=='
            typ='bool' if isinstance(value,bool) else 'std::string'
            condition=f'root[{json.dumps(rule["field"])}].as<{typ}>() {cmp} {json.dumps(value)}'
            if 'unlessEquals' in rule:condition=f'(!root.containsKey({json.dumps(rule["field"])}) || {condition})'
            out.append(f'    if ({condition}) {{\n')
            for key in rule['required']:out.append(f'      if (!root.containsKey({json.dumps(key)})) return std::nullopt;\n')
            out.append('    }\n')
        out.append(f'    {ident} result;\n')
        for key,spec in m['fields'].items():
            value=f'root[{json.dumps(key)}]'
            if spec['type']=='array':
                out.append(f'    for (JsonVariantConst item : {value}.as<JsonArrayConst>()) {{\n')
                if spec['items']['type']=='object':
                    members=', '.join(read(v,f'item[{json.dumps(k)}]',ident) for k,v in spec['items']['fields'].items())
                    out.append(f'      result.{key}.push_back({{{members}}});\n')
                else:out.append(f'      result.{key}.push_back({read(spec["items"],"item",ident)});\n')
                out.append('    }\n')
            else:
                prefix=f'if (root.containsKey({json.dumps(key)})) ' if spec.get('optional') else ''
                out.append(f'    {prefix}result.{key} = {read(spec,value,ident)};\n')
        out.append('    return result;\n  }\n')
    out.append('  return std::nullopt;\n}\n}  // namespace companion_protocol\n')
    # ArduinoJson 7 containsKey is deprecated; optional presence must distinguish null.
    result=''.join(out)
    result=re.sub(r'root\.containsKey\(("[^"]+")\)',r'!root[\1].isUnbound()',result)
    return result


def swift(data):
    out=['''// GENERATED by scripts/build.py companion. Do not edit.
import Foundation
import CoreFoundation

enum CompanionProtocolState: String { case pairing, authenticating, connected }
enum CompanionProtocolDirection: String { case panelToMac = "panel_to_mac", macToPanel = "mac_to_panel" }
''']
    def typ(spec,ident):
        k=spec['type']
        if k=='object':struct(ident,spec['fields']);return ident
        if k=='array':return '['+typ(spec['items'],ident+'Item')+']'
        return {'string':'String','integer':'UInt32','number':'Double','boolean':'Bool'}[k]
    def struct(ident,fields):
        decl=[]
        for key,spec in fields.items():decl.append('    let '+key+': '+typ(spec,ident+name(key))+('?' if spec.get('optional') else ''))
        out.append('struct CompanionWire'+ident+': Codable, Sendable {\n'+'\n'.join(decl)+'\n}\n')
    # Nested type names need the same prefix as top-level declarations.
    for m in data['protocol']['messages']:struct(name(m['id']),m['fields'])
    out.append('enum CompanionProtocolMessage: Sendable {\n')
    for m in data['protocol']['messages']:
        n=name(m['id']);out.append(f'    case {n[0].lower()+n[1:]}(CompanionWire{n})\n')
    out.append('}\n')
    # Validation is generated from the same field rules as the C++ decoder.
    schema=json.dumps(data['protocol']['messages'],separators=(',',':'))
    out.append('''enum CompanionProtocolDecoder {
    private static let schemaData = #"'''+schema+'''"#.data(using: .utf8)!
    private static let schemas = try! JSONSerialization.jsonObject(with: schemaData) as! [[String: Any]]

    private static func valid(_ value: Any, _ rule: [String: Any]) -> Bool {
        switch rule["type"] as? String {
        case "string":
            guard let text = value as? String, !text.utf8.contains(0),
                  text.utf8.count >= rule["minLength"] as! Int,
                  text.utf8.count <= rule["maxLength"] as! Int else { return false }
            if let options = rule["enum"] as? [String], !options.contains(text) { return false }
            if rule["pattern"] as? String == "hex64" {
                return text.utf8.count == 64 && text.utf8.allSatisfy { (48...57).contains($0) || (65...70).contains($0) || (97...102).contains($0) }
            }
            return true
        case "integer", "number":
            guard let number = value as? NSNumber, CFGetTypeID(number) != CFBooleanGetTypeID() else { return false }
            let n = number.doubleValue
            return n.isFinite && n >= (rule["minimum"] as! NSNumber).doubleValue && n <= (rule["maximum"] as! NSNumber).doubleValue && (rule["type"] as? String != "integer" || n.rounded(.towardZero) == n)
        case "boolean":
            guard let number = value as? NSNumber else { return false }
            return CFGetTypeID(number) == CFBooleanGetTypeID()
        case "array":
            guard let values = value as? [Any], values.count <= rule["maxItems"] as! Int,
                  let item = rule["items"] as? [String: Any] else { return false }
            return values.allSatisfy { valid($0, item) }
        case "object":
            guard let object = value as? [String: Any], let fields = rule["fields"] as? [String: [String: Any]] else { return false }
            return validFields(object, fields)
        default: return false
        }
    }
    private static func validFields(_ object: [String: Any], _ fields: [String: [String: Any]]) -> Bool {
        for (key, rule) in fields {
            guard let value = object[key] else {
                if rule["optional"] as? Bool == true { continue }
                return false
            }
            if !valid(value, rule) { return false }
        }
        return true
    }
    static func decode(_ data: Data, direction: CompanionProtocolDirection, state: CompanionProtocolState) -> CompanionProtocolMessage? {
        guard data.count <= CompanionCapabilities.maximumTextFrameBytes,
              let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let version = object["protocol"] as? NSNumber, CFGetTypeID(version) != CFBooleanGetTypeID(),
              version.doubleValue == Double(CompanionCapabilities.protocolVersion),
              let type = object["type"] as? String,
              let rule = schemas.first(where: { $0["id"] as? String == type }),
              let states = rule["states"] as? [String], states.contains(state.rawValue),
              let fields = rule["fields"] as? [String: [String: Any]],
              rule["direction"] as? String == direction.rawValue || rule["direction"] as? String == "bidirectional",
              validFields(object, fields) else { return nil }
        for condition in rule["requiresWhen"] as? [[String: Any]] ?? [] {
            let actual = object[condition["field"] as! String] as? NSObject
            let matches: Bool
            if let expected = condition["equals"] as? NSObject { matches = actual == expected }
            else { matches = actual != condition["unlessEquals"] as? NSObject }
            if matches && !(condition["required"] as! [String]).allSatisfy({ object[$0] != nil }) { return nil }
        }
        let decoder = JSONDecoder()
        switch type {
''')
    for m in data['protocol']['messages']:
        n=name(m['id']);out.append(f'        case {json.dumps(m["id"])}: return (try? decoder.decode(CompanionWire{n}.self, from: data)).map(CompanionProtocolMessage.{n[0].lower()+n[1:]})\n')
    out.append('        default: return nil\n        }\n    }\n}\n')
    result=''.join(out)
    # Nested catalogue entries are generated alongside the message structures.
    result=result.replace('[CataloguePageItemsItem]','[CompanionWireCataloguePageItemsItem]')
    # Foundation dictionaries are immutable after initialization, but Any does not express Sendable.
    result=result.replace('private static let schemas', 'nonisolated(unsafe) private static let schemas')
    return result


def outputs(root, data):
    validate_contract(data)
    return [
        (root/'components/espcontrol/companion_protocol_generated.h',cpp(data)),
        (root/'macos/Companion/Sources/Companion/CompanionProtocol.generated.swift',swift(data)),
    ]
