#!/usr/bin/env python3
"""Generate the Swift Companion contract sources from the shared protocol file."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from companion_protocol_codegen import swift as generate_protocol_swift


ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "product/v2/companion_capabilities.json"
CAPABILITIES_SWIFT = ROOT / "Sources/Companion/CompanionCapabilities.generated.swift"
PROTOCOL_SWIFT = ROOT / "Sources/Companion/CompanionProtocol.generated.swift"


def generate_capabilities_swift(data: dict) -> str:
    flag_names = {
        "command": ".maskCommand",
        "control": ".maskControl",
        "option": ".maskAlternate",
        "shift": ".maskShift",
        "function": ".maskSecondaryFn",
    }
    lines = [
        "// GENERATED COMPANION CAPABILITIES - do not edit by hand\n",
        "// Generated by scripts/generate_companion.py from product/v2/companion_capabilities.json.\n\n",
        "import CoreGraphics\n\n",
        "struct CompanionWindowActionCapability {\n",
        "    let key: String\n",
        "    let flags: CGEventFlags\n",
        "    let minimumMacOS: Int\n",
        "}\n\n",
        "enum CompanionCapabilities {\n",
        f"    static let version = {data['version']}\n",
        f"    static let protocolVersion = {data['protocol']['version']}\n",
        f"    static let protocolPath = {json.dumps(data['protocol']['path'])}\n",
        f"    static let maximumTextFrameBytes = {data['protocol']['maximumTextFrameBytes']}\n",
        f"    static let maximumArtworkBytes = {data['protocol']['maximumArtworkBytes']}\n",
        f"    static let artworkChunkBytes = {data['protocol']['artworkChunkBytes']}\n",
        f"    static let pairingWindowSeconds = {data['security']['pairingWindowSeconds']}\n",
        "    static let protocolMessages: Set<String> = [\n",
    ]
    lines.extend(f"        {json.dumps(item['id'])},\n" for item in data["protocol"]["messages"])
    lines.extend(["    ]\n", "    static let cardModes: [String: String] = [\n"])
    lines.extend(
        f"        {json.dumps(item['id'])}: {json.dumps(item['label'])},\n"
        for item in data["cardModes"]
    )
    lines.extend(["    ]\n", "    static let windowActions: [String: CompanionWindowActionCapability] = [\n"])
    for item in data["windowActions"]:
        flags = ", ".join(flag_names[modifier] for modifier in item["modifiers"])
        lines.append(
            f"        {json.dumps(item['id'])}: .init(key: {json.dumps(item['key'])}, "
            f"flags: [{flags}], minimumMacOS: {item['minimumMacOS']}),\n"
        )
    lines.extend(["    ]\n", "    static let mediaCommandByActionID: [String: String] = [\n"])
    lines.extend(
        f"        {json.dumps(item['id'])}: {json.dumps(item['command'])},\n"
        for item in data["mediaActions"]
    )
    lines.extend(
        [
            "    ]\n",
            f"    static let mediaPlayPauseID = {json.dumps(data['mediaActions'][0]['id'])}\n",
            "}\n",
        ]
    )
    return "".join(lines)


def generated_outputs() -> list[tuple[Path, str]]:
    data = json.loads(CONTRACT.read_text(encoding="utf-8"))
    return [
        (CAPABILITIES_SWIFT, generate_capabilities_swift(data)),
        (PROTOCOL_SWIFT, generate_protocol_swift(data)),
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()

    stale: list[Path] = []
    for path, content in generated_outputs():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        stale.append(path)
        if not args.check:
            path.write_text(content, encoding="utf-8")

    if args.check and stale:
        print("Generated Companion sources are out of date:")
        for path in stale:
            print(f"  {path.relative_to(ROOT)}")
        return 1
    if stale:
        print("Updated generated Companion sources:")
        for path in stale:
            print(f"  {path.relative_to(ROOT)}")
    else:
        print("Generated Companion sources are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
