"""Validate editable Web App templates and generate their bundled starter catalogue."""
from __future__ import annotations

import json
import re
from pathlib import Path

from app_shortcuts_codegen import icon_names, shortcut_valid, validate_manifest


def load_web_apps(root: Path):
    directory = root / "product/v2/web_apps"
    icons = icon_names(json.loads((root / "product/v2/icons.json").read_text()))
    apps, seen = [], set()
    for path in sorted(directory.glob("*.json")):
        if path.name == "manifest.json":
            continue
        app = json.loads(path.read_text())
        required = {"version", "id", "label", "url", "matchHost", "icon", "shortcuts"}
        allowed = required | {"matchPath"}
        if not isinstance(app, dict) or not required <= set(app) or set(app) - allowed:
            raise ValueError(f"{path.name}: expected version, id, label, url, matchHost, icon, shortcuts, and optional matchPath")
        if type(app["version"]) is not int or app["version"] != 1:
            raise ValueError(f"{path.name}: version must be 1")
        if (not isinstance(app["id"], str) or len(app["id"].encode("utf-8")) > 64 or
                not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", app["id"])):
            raise ValueError(f"{path.name}: id must be a lowercase hyphenated identifier of at most 64 bytes")
        if app["id"] in seen:
            raise ValueError(f"{path.name}: duplicate Web App id {app['id']}")
        seen.add(app["id"])
        if not isinstance(app["label"], str) or not app["label"].strip() or len(app["label"].encode("utf-8")) > 48:
            raise ValueError(f"{path.name}: label must contain 1–48 bytes of text")
        if not isinstance(app["url"], str) or not app["url"].startswith("https://"):
            raise ValueError(f"{path.name}: url must use HTTPS")
        from urllib.parse import urlparse
        parsed_url = urlparse(app["url"])
        if not parsed_url.hostname or parsed_url.username or parsed_url.password:
            raise ValueError(f"{path.name}: url must be a public HTTPS address")
        if not isinstance(app["matchHost"], str) or app["matchHost"] != app["matchHost"].lower() or not re.fullmatch(r"[a-z0-9.-]+", app["matchHost"]):
            raise ValueError(f"{path.name}: matchHost must be a lowercase hostname")
        if parsed_url.hostname.lower() != app["matchHost"]:
            raise ValueError(f"{path.name}: matchHost must match the launch URL host")
        match_path = app.get("matchPath")
        if match_path is not None and (not isinstance(match_path, str) or not match_path.startswith("/") or "?" in match_path or "#" in match_path):
            raise ValueError(f"{path.name}: matchPath must be a URL path prefix")
        prefix = f"https://raw.githubusercontent.com/jtenniswood/espdesktop/main/product/v2/web_apps/icons/"
        icon_path = directory / "icons" / app["icon"].removeprefix(prefix) if isinstance(app["icon"], str) else directory / "icons" / ""
        if not isinstance(app["icon"], str) or not app["icon"].startswith(prefix) or icon_path.suffix.lower() not in {".png", ".jpg", ".jpeg"} or not icon_path.resolve().is_relative_to((directory / "icons").resolve()) or not icon_path.is_file():
            raise ValueError(f"{path.name}: icon must point to a hosted file in product/v2/web_apps/icons")
        shortcuts = app["shortcuts"]
        if not isinstance(shortcuts, list) or not 1 <= len(shortcuts) <= 64:
            raise ValueError(f"{path.name}: shortcuts must contain 1–64 entries")
        ids = set()
        for shortcut in shortcuts:
            if not isinstance(shortcut, dict) or set(shortcut) != {"id", "label", "shortcut", "icon"}:
                raise ValueError(f"{path.name}: every shortcut needs id, label, shortcut, icon")
            ident = shortcut["id"]
            if not isinstance(ident, str) or not re.fullmatch(r"0|[1-9][0-9]{0,2}", ident) or ident in ids:
                raise ValueError(f"{path.name}: shortcut ids must be unique numbers from 0 to 999")
            ids.add(ident)
            if (not isinstance(shortcut["label"], str) or not shortcut["label"].strip() or
                    len(shortcut["label"].encode("utf-8")) > 48 or
                    not shortcut_valid(shortcut["shortcut"]) or shortcut["icon"] not in icons):
                raise ValueError(f"{path.name}: invalid shortcut {ident}")
        if len(json.dumps(app, ensure_ascii=False, separators=(",", ":")).encode("utf-8")) > 12000:
            raise ValueError(f"{path.name}: compact serialized definition exceeds 12000 bytes")
        apps.append(app)
    validate_manifest(directory, {path.name for path in directory.glob("*.json") if path.name != "manifest.json"})
    return sorted(apps, key=lambda app: (app["label"].casefold(), app["id"]))


def outputs(root: Path):
    apps = load_web_apps(root)
    ts = "// Generated by scripts/build.py companion from product/v2/web_apps/*.json. Do not edit.\n"
    ts += "export interface WebAppShortcut { readonly id: string; readonly label: string; readonly shortcut: string; readonly icon: string; }\n"
    ts += "export interface WebAppDefinition { readonly version: number; readonly id: string; readonly label: string; readonly url: string; readonly matchHost: string; readonly matchPath?: string; readonly icon: string; readonly shortcuts: readonly WebAppShortcut[]; }\n"
    ts += "export const COMPANION_WEB_APPS: readonly WebAppDefinition[] = " + json.dumps(apps, indent=2, ensure_ascii=False) + ";\n"
    cpp = ["#pragma once", "// Generated by scripts/build.py companion from product/v2/web_apps/*.json. Do not edit.", "#include <string>", "namespace companion_web_app_catalog {", "inline const char *icon_url(const std::string &id) {"]
    for app in apps:
        cpp.append(f"  if (id == {json.dumps(app['id'])}) return {json.dumps(app['icon'])};")
    cpp.extend(["  return \"\";", "}", "}"])
    result = [(root / "src/webserver/generated/web_apps.ts", ts),
              (root / "components/espdesktop/web_apps_generated.h", "\n".join(cpp) + "\n")]
    resources = root / "macos/EspDesktop/Sources/Companion/Resources/WebApps"
    manifest = root / "product/v2/web_apps/manifest.json"
    if manifest.exists():
        result.append((resources / "manifest.json", manifest.read_text()))
    for path in sorted((root / "product/v2/web_apps").glob("*.json")):
        if path.name != "manifest.json":
            result.append((resources / path.name, path.read_text()))
    return result
