// GENERATED COMPANION CAPABILITIES - do not edit by hand
// Generated by scripts/build.py from product/v2/companion_capabilities.json.

import CoreGraphics

struct CompanionWindowActionCapability {
    let key: String
    let flags: CGEventFlags
    let minimumMacOS: Int
}

enum CompanionCapabilities {
    static let version = 1
    static let windowActions: [String: CompanionWindowActionCapability] = [
        "window.close": .init(key: "w", flags: [.maskCommand], minimumMacOS: 13),
        "window.minimize": .init(key: "m", flags: [.maskCommand], minimumMacOS: 13),
        "window.hide": .init(key: "h", flags: [.maskCommand], minimumMacOS: 13),
        "window.fullscreen": .init(key: "f", flags: [.maskControl, .maskCommand], minimumMacOS: 13),
        "window.fill": .init(key: "f", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15),
        "window.center": .init(key: "c", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15),
        "window.left": .init(key: "left", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15),
        "window.right": .init(key: "right", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15),
        "window.top": .init(key: "up", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15),
        "window.bottom": .init(key: "down", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15),
        "window.restore": .init(key: "r", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15),
        "window.arrange.left-right": .init(key: "left", flags: [.maskSecondaryFn, .maskControl, .maskShift], minimumMacOS: 15),
        "window.arrange.right-left": .init(key: "right", flags: [.maskSecondaryFn, .maskControl, .maskShift], minimumMacOS: 15),
        "window.arrange.top-bottom": .init(key: "up", flags: [.maskSecondaryFn, .maskControl, .maskShift], minimumMacOS: 15),
        "window.arrange.bottom-top": .init(key: "down", flags: [.maskSecondaryFn, .maskControl, .maskShift], minimumMacOS: 15),
        "window.arrange.left-quarters": .init(key: "left", flags: [.maskSecondaryFn, .maskControl, .maskAlternate, .maskShift], minimumMacOS: 15),
        "window.arrange.right-quarters": .init(key: "right", flags: [.maskSecondaryFn, .maskControl, .maskAlternate, .maskShift], minimumMacOS: 15),
        "window.arrange.top-quarters": .init(key: "up", flags: [.maskSecondaryFn, .maskControl, .maskAlternate, .maskShift], minimumMacOS: 15),
        "window.arrange.bottom-quarters": .init(key: "down", flags: [.maskSecondaryFn, .maskControl, .maskAlternate, .maskShift], minimumMacOS: 15),
    ]
    static let mediaCommandByActionID: [String: String] = [
        "media.play_pause": "togglePlayPause",
        "media.previous": "previousTrack",
        "media.next": "nextTrack",
    ]
    static let mediaPlayPauseID = "media.play_pause"
}
