// GENERATED COMPANION CAPABILITIES - do not edit by hand
// Generated by scripts/build.py from product/v2/companion_capabilities.json.

import CoreGraphics

struct CompanionWindowActionCapability {
    let key: String
    let flags: CGEventFlags
    let minimumMacOS: Int
}

enum CompanionCapabilities {
    static let version = 2
    static let protocolVersion = 3
    static let protocolPath = "/companion/v3"
    static let maximumTextFrameBytes = 16384
    static let maximumArtworkBytes = 262144
    static let artworkChunkBytes = 12288
    static let pairingWindowSeconds = 900
    static let protocolMessages: Set<String> = [
        "hello",
        "pair.request",
        "pair.accepted",
        "auth.request",
        "auth.accepted",
        "capabilities",
        "catalogue.page",
        "action.invoke",
        "action.result",
        "value.set",
        "value.state",
        "focus.changed",
        "timezone.changed",
        "now_playing",
        "system_metrics",
        "artwork.begin",
        "artwork.ack",
        "artwork.end",
        "artwork.abort",
        "artwork.request",
        "error",
    ]
    static let cardModes: [String: String] = [
        "app": "Launch app",
        "shortcut": "Keyboard shortcut",
        "url": "Open URL",
        "folder": "Open folder",
        "media": "Media control",
        "stats": "Stats",
        "window": "Window control",
    ]
    static let windowActions: [String: CompanionWindowActionCapability] = [
        "window.close": .init(key: "w", flags: [.maskCommand], minimumMacOS: 13),
        "window.minimize": .init(key: "m", flags: [.maskCommand], minimumMacOS: 13),
        "window.hide": .init(key: "h", flags: [.maskCommand], minimumMacOS: 13),
        "window.fullscreen": .init(key: "f", flags: [.maskControl, .maskCommand], minimumMacOS: 13),
        "window.fill": .init(key: "f", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15),
        "window.center": .init(key: "c", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15),
        "window.left": .init(key: "left", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15),
        "window.right": .init(key: "right", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15),
        "window.top": .init(key: "up", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15),
        "window.bottom": .init(key: "down", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15),
        "window.restore": .init(key: "r", flags: [.maskSecondaryFn, .maskControl], minimumMacOS: 15),
        "window.arrange.left-right": .init(key: "left", flags: [.maskSecondaryFn, .maskControl, .maskShift], minimumMacOS: 15),
        "window.arrange.right-left": .init(key: "right", flags: [.maskSecondaryFn, .maskControl, .maskShift], minimumMacOS: 15),
        "window.arrange.top-bottom": .init(key: "up", flags: [.maskSecondaryFn, .maskControl, .maskShift], minimumMacOS: 15),
        "window.arrange.bottom-top": .init(key: "down", flags: [.maskSecondaryFn, .maskControl, .maskShift], minimumMacOS: 15),
        "window.arrange.left-quarters": .init(key: "left", flags: [.maskSecondaryFn, .maskControl, .maskAlternate, .maskShift], minimumMacOS: 15),
        "window.arrange.right-quarters": .init(key: "right", flags: [.maskSecondaryFn, .maskControl, .maskAlternate, .maskShift], minimumMacOS: 15),
        "window.arrange.top-quarters": .init(key: "up", flags: [.maskSecondaryFn, .maskControl, .maskAlternate, .maskShift], minimumMacOS: 15),
        "window.arrange.bottom-quarters": .init(key: "down", flags: [.maskSecondaryFn, .maskControl, .maskAlternate, .maskShift], minimumMacOS: 15),
    ]
    static let mediaCommandByActionID: [String: String] = [
        "media.play_pause": "togglePlayPause",
        "media.previous": "previousTrack",
        "media.next": "nextTrack",
    ]
    static let mediaPlayPauseID = "media.play_pause"
}
